[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/simulator"
  to = "/simulator.html"
  status = 301
[[redirects]]
  from = "/tarifs"
  to = "/tarifs.html"
  status = 301
[[redirects]]
  from = "/mentions"
  to = "/mentions.html"
  status = 301
  [[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]
